### Q1:   What is a vector?
#### Ans:

A vector is a one dimentional array of list.

### Q2: How do you represent vectors using a Python list? Give an example
#### Ans:

Numpy library will be required.
    
list1 = [1, 3, 5, 7, 9]

list2 = [2, 4, 6, 8, 10]

vct1 = np.array(list1)

vct2 = np.array(list2)

To view the result, print() function will be used with the following syntax,

print("Vector created from list1:  ", (vct1))

print ("Vector created from list2:  ", (vct2))

### Example of Q2

In [1]:
# example of Q2
import numpy as np
    
list1 = [1, 3, 5, 7, 9]

list2 = [2, 4, 6, 8, 10]

vct1 = np.array(list1)

vct2 = np.array(list2)

print("Vector created from list1:  ", (vct1))

print ("Vector created from list2:  ", (vct2))

Vector created from list1:   [1 3 5 7 9]
Vector created from list2:   [ 2  4  6  8 10]


### Q3: What is a dot product of two vectors?
#### Ans:

The dot product is the multiplication of two equal vectors.

It is the sum of the product of corresponding elements of vectors.

vct3 = np.array ([a, b, c, d])

vct4 = np.array ([e, f, g, h])

the dot product of vct3 * vct4 (multiplying crossponding elements of vectors and

adding the product of vectors = (a * e)  + (b * f) + (c * g) + (d * h) 

### Q4:  Write a function to compute the dot product of two vectors
#### Ans:

Answer is given below;

In [8]:
#Ans Q4:

import numpy as np
vct3 = ([1, 5, 10, 15])
vct4 = ([4, 8, 16, 32])
#the dot product of vct3 * vct4 (multiplying crossponding elements of vectors and adding the product
#the dot() function will be used to calculate the product of vectors in python

print (np. dot(vct3, vct4))

684


### Q5: What is Numpy

#### Ans:

Numpy is a Python library (short for numerical python). It is suitable to store more data in less memory and used for scientific computing and can perform mathematical and logical operations on arrays and linear algebra calculations etc.  

### Q6: How do you install Numpy?

#### Ans:

The sytax to install numpy is;
    
!pip install numpy

### Q7: How do you import the numpy module?
#### Ans:

To import numpy library, following syntax is used,

import numpy 

or

import numpy as np 

(Note: np is the alias keyword of numpy)

### Q8: What does it mean to import a module with an alias? Give an example
#### Ans: 

It is best practice to import module with an alias of short keywords so that it can be used easily while in coding and save time to repeat module name every time when required.

For example if we import numpy as np, we will use np keyword every time insted of typing numpy.

e.g 

import numpy as np

arr1 = np.array ([1 ,2, 3, 4, 5])

otherwise we have to type arr1 = numpy.array ([1, 2, 3, 4, 5])

### Q9: What is the commonly used alias for numpy?
#### Ans:

The commonly used alias for numpy library module is np

### Q10: What is a Numpy array? 
#### Ans:

A numpy array is a grid of value indexed by a tuple of +ive integers. Arrays can have more than one dimentions.

The number of dimensions is the rank of the array.

The shape of an array is a tuple of integers giving the size of the array along each dimension.

### Q11: How do you create a Numpy array? Give an example.
#### Ans:


Numpy array can be created using the array constructor, numpy.array() or np.array() if alias np is being used.

import numpy as np

arr = np.array(seq, dtype)

arr = np.array([])             

to create an empty array

### Q12: What is the type of Numpy arrays?
#### Ans:

The default type of numpy array is float, however other types are integer, boolean, complex float etc. 

### Q13: How do you access the elements of a Numpy array?
#### Ans:

The elements of the array can be accessed with their relevant index numbers (starting from 0)

### Q14: How do you compute the dot product of two vectors using Numpy?
#### Ans:

First of all we need to import numpy module as np, then we need to create vectors with the help of np.array and then  calculate the dot product of two vectors by adding the product of their respective elements.

e.g.

import numpy as np

vct1 = np.array([13, 5, 10, 7])
vct2 = np.array([8, 9, 11, 55])

#dot product of vct1 and vct2 with the help of dot() function

print (np.dot(vct1, vct2))

Note: a complete example is given below

In [45]:
# Example of dot() function

import numpy as np

vct1 = np.array([13, 5, 10, 77])
vct2 = np.array([8, 9, 11, 55])

#dot product of vct1 and vct2 with the help of dot() function
#print (np. dot(vct3, vct4))

print (np. dot(vct1, vct2))

4494


### Q15: What happens if you try to compute the dot product of two vectors which have different sizes?
#### Ans:

Since the dot product of vectors is the multiplication of elements at the same position, therefore two vectors must have the same length. 

If we try to obtain dot product of vectors having differen size of length, the programm will give an error.

### Q16: How do you compute the element-wise product of two Numpy arrays?
#### Ans:

The element wise product of two numpy arrays can be obtained with the help of multiply() function.

the example is given below:

In [20]:
# Example of multiply() function

import numpy as np
arr5 = np.array ([3, 5, 6, 9])
arr6 = np.array ([45, 66, 77, 88])
mlpy = np.multiply (arr5, arr6)
print ("The product of two arrays:  ",mlpy)



The product of two arrays:   [135 330 462 792]


### Q17: How do you compute the sum of all the elements in a Numpy array?
#### Ans:

The sum() function is used to calculate the sum of all elements in the numpy array as shown in the below example.

In [50]:
# Example of sum() function

import numpy as np
arr7 = np.array ([11, 43, 55, 47, 78])

print("Sum of all elements in the array =  ",np.sum(arr7))

Sum of all elements in the array =   234


### Q18: What are the benefits of using Numpy arrays over Python lists for operating on numerical data?
#### Ans:

Using Numpy arrays makes program more efficient as commpare to using Python Lists because Numpy arrays are stored at one continuous place in the memory where as data in a list stored in random areas of memory which makes it slower to access.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### Q19: Why do Numpy array operations have better performance compared to Python functions and loops?
#### Ans:

The numpy is optimized for certain operations, whereas lists are created as  generic. When numpy performs a calculation on an array it knows exactly what it contains (integers or floats - actual values stored in memory in arranged manner), and  also know the size of the array but when Python performs calculation in the list it knows that it contains objects, and it has further steps to adopt before it is able to execute an operation. Therefore, there are significant performance differences.

### Q20: Illustrate the performance difference between Numpy array operations and Python loops using an example. 

#### Ans:

 Following is the calcualted comparison of list and array


In [64]:
#Example for Q20:

import numpy as np
import sys

list1= range(5000)

print("(Python List occupying memory)")

# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(list1))


# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(list1)*len(list1))
print()

print("(numpy Array occupying memory)")
array = np.arange(5000)

# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",array.itemsize)

# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",array.size*array.itemsize)


(Python List occupying memory)
Size of each element of list in bytes:  48
Size of the whole list in bytes:  240000

(numpy Array occupying memory)
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  20000


In [66]:
#Code copied from some other website

import numpy as np
import timeit


def sum_with_for_loop(array) -> int:
    sum = 0
    for i in array:
        sum += i
    return sum


def sum_with_np_sum(array) -> int:
    return np.sum(array)


if __name__ == "__main__":
    array = np.random.randint(0, 100, 1000000)

    # print time for for loop
    print(timeit.timeit(lambda: sum_with_for_loop(array), number=100))

    # print time for np.sum
    print(timeit.timeit(lambda: sum_with_np_sum(array), number=100))

22.4089422999823
0.06902080000145361


### Q21: What are multi-dimensional Numpy arrays? 
#### Ans:

A multi-dimensional array is an array with more than one level or dimension. These arrays are also called matrices and  are powerfull data structure in Python.

### Q22: Illustrate the creation of Numpy arrays with 2, 3, and 4 dimensions.
#### Ans:

Following are the examples of creating multidimension arrays; 

In [108]:
import numpy as np

# mdarr stands for multidimension array
mdarr1 = np.array([[1, 13, 15, 20], [11, 12, 13, 14]]) # example of 2D array creation

mdarr2 = np.array([[[1, 13, 15, 20], [11, 12, 13, 14], [22, 23, 24, 25]]]) # example of 3D array creation

mdarr3 = np.array([[[[1, 13, 15, 20], [11, 12, 13, 14], [22, 23, 24, 25], [33, 44, 55, 66]]]]) # example of 4D array creation

print ("Calculate dimensions of the array 'mdarr1' =  " , (mdarr1.ndim))
print()
print ("Calculate dimensions of the array 'mdarr2' =  " , (mdarr2.ndim))
print()
print ("Calculate dimensions of the array 'mdarr3' =  " , (mdarr3.ndim))  

Calculate dimensions of the array 'mdarr1' =   2

Calculate dimensions of the array 'mdarr2' =   3

Calculate dimensions of the array 'mdarr3' =   4


### Q23: How do you inspect the number of dimensions and the length along each dimension in a Numpy array?
#### Ans:

We use following attribute to find out the dimensions of Numpy Array;

array_name.ndim 

We use following length function to find out the length of Array;

length = array_name.__len__()

### Q24: Can the elements of a Numpy array have different data types? 
#### Ans:
No.

(infact all elements of the array are of same data type and should be homogeneous) 

### Q25: How do you check the data type of the elements of a Numpy array?
#### Ans:

dtype attribute is used to check the data type of an array.

following is the example,

In [127]:
import numpy as np
arr1 = np.array(['a' , 'b', 'c', 'd', 'e'])
arr2 = np.array([1, 3, 5, 7, 9])
print('Array:', arr1)
print('Datatype:', arr1.dtype)
print()
print('Array:', arr2)
print('Datatype:', arr2.dtype)



Array: ['a' 'b' 'c' 'd' 'e']
Datatype: <U1

Array: [1 3 5 7 9]
Datatype: int32


### Q26: What is the data type of a Numpy array? 
#### Ans:

 Numpy array can be of one of the follwoing basic data types,
 
 Bool
 
 int (int8, int32, int64)
 
 float (float16, float32, float64, float128)
 
 object
 
 string
 
 unicode 
 
 etc.
 

### Q27: What is the difference between a matrix and a 2D Numpy array? 
#### Ans:

Numpy arrays are 1D, 2D, 3D, 4D........nD (dimensions) but matrices are only 2 dimensional only.

Matrix elements are subclass of nd-array.

### Q28: How do you perform matrix multiplication using Numpy?
#### Ans:

The multplying of matrices can be done in Numpy with the help of vectorisation of matrices

### Q29: What is the @ operator used for in Numpy?
#### Ans:

The @ operator is used for matrix multiplications


### Q30: What is the CSV file format? 
#### Ans:

csv stands for comma seperated value file format.

### Q31: How do you read data from a CSV file using Numpy?
#### Ans:

First of all we need to install and import panda library.

We can use read_csv() function to read the csv file according to the following syntax;

!pip install pandas

import pandas as pd

spreadsheet = pd.read_csv(filename.csv)

spreadsheet.head() is used to view the file

### Q32: How do you concatenate two Numpy arrays?
#### Ans:

Numpy arrays can be concatenated with the help of concatenate() function.

In [9]:
#Example of Q 32


import numpy as np

arr11 = np.array([11, 12, 13])

arr12 = np.array([14, 15, 16])

arr = np.concatenate((arr11, arr12))

print(arr)

[11 12 13 14 15 16]


### Q33: What is the purpose of the axis argument of np.concatenate?
#### Ans:

Concatenating of Numpy arrays is like stacking of arrays. The axis perameter we define along with the stack of the arrays.

If axis = 0 it run vertically down the rows.

### Q34:  When are two Numpy arrays compatible for concatenation?
#### Ans:

The arrays of the same shape are compatible for concatenation, except in the dimension corresponding to axis.

To check if all elements of two NumPy arrays are equal: np. array_equal() , np. array_equiv() You can check if all elements of two NumPy arrays are equal with == and np.

### Q35: Give an example of two Numpy arrays that can be concatenated.
#### Ans:

For example 

arr13 = np.array([[1, 2, 3], [4, 5, 6]])

arr14 = np.array([[7, 8, 9], [10, 11, 12]])



In [11]:
# Example of compatible numpy arrays

import numpy as np

arr13 = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("First numpy arrays:\n", arr13)
arr14 = np.array([[7, 8, 9],
                  [10, 11, 12]])
print("Second numpy arrays:\n", arr14)

result = np.concatenate((arr13, arr14), axis=1)
print("After concatenating the array along axis 1:\n", result)

First numpy arrays:
 [[1 2 3]
 [4 5 6]]
Second numpy arrays:
 [[ 7  8  9]
 [10 11 12]]
After concatenating the array along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Q36: Give an example of two Numpy arrays that cannot be concatenated
#### Ans:

The arrays having NumPy "ValueError: zero-dimensional arrays cannot be concatenated" occurs when you pass a single one-dimensional array to the numpy. concatenate() method.

### Q37: What is the purpose of the np.reshape function?
#### Ans:

We can add or remove dimensions or change number of elements in each dimension with the help of reshape function.

### Q38: What does it mean to “reshape” a Numpy array?
#### Ans:

Reshaping means changing the shape of an array. The shape of an array is the number of elements in each dimension. Number of elements or dimensions can be added or removed to reshape the Numpy arrays.


### Q39: How do you write a numpy array into a CSV file?
#### Ans:

With the help of panda library we can write Numpy array into csv file as per follwoing steps;

import numpy as np 

import pandas as pd.

Create a 2D numpy array data = np. array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) e.g

Convert numpy array to pandas DataFrame df = pd. DataFrame(data)

Save DataFrame to .csv df. to_csv('data.csv', index=False)

### Q40: Give some examples of Numpy functions for performing mathematical operations
#### Ans:
Python has a wide range of standard arithmetic operations like addition, subtraction, multiplication, and divisions etc.
There are specific functions in NumPy for performing arithmetic operations. 

In [13]:
# examples of Q40

#NumPy Add function

import numpy as np
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
print(np.add(a, b))


[ 13  24 105 206 507]


In [15]:
# examples of Q40 (Contn..)
#NumPy Subtract function

import numpy as np
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
print(np.subtract(a, b))


[  7  16  95 194 493]


In [16]:
# examples of Q40 (Contn..)

#NumPy Multiply function

import numpy as np
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
print (np.multiply(a, b))


[21 12 20 30  7]


In [17]:
# examples of Q40 (Contn..)

#NumPy Divide Function

import numpy as np
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
print(np.divide(a,b))

[2.33333333 0.75       0.8        0.83333333 0.14285714]


In [18]:
#NumPy Remainder Function
import numpy as np
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
print(np.remainder(a,b))

[1 3 4 5 1]


In [20]:
# examples of Q40 (Contn..)

#NumPy Mod Function
import numpy as np
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
print(np.mod(a,b))

[1 3 4 5 1]


### Q41: Give some examples of Numpy functions for performing array manipulation
#### Ans:

We can manipulate arrays by changing thier order or by reshaping them,


numpy. reshape()

numpy. flip()

numpy. transpose()

In [29]:
# example of Q41

# The numpy. reshape() function to reshape a array

import numpy as np

arr13 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

arr14 = arr13.reshape(4, 4)

print(arr14)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
# example of Q41 (cont.)

#The numpy. flip() function reverses the order of array elements along the specified axis

import numpy as np

# Create an 1D input array  
arr15 = np.array([2, 4, 6, 8, 10])

# Use numpy flip() function on 1-d array
arr16= np.flip(arr)
print(arr16)

[16 15 14 13 12 11]


In [27]:
# example of Q41 (cont.)

#The numpy. transpose() function swap the axix of arrays

import numpy as np

orgarr = np.array([[3, 2], [5, 4]])

# swaps the rows and columns of an array
transposedArray = np.transpose(orgarr)

print(transposedArray)

[[3 5]
 [2 4]]


### Q42: Give some examples of Numpy functions for performing linear algebra
#### Ans:

Numpy can perform linear algebric function such as,


dot()	calculates product of two arrays

inner()	calculates inner product of arrays

outer()	calculates outer product of arrays

det()	calculates determinant of a matrix

solve()	solves linear matrix equation

inv()	calculates the multiplicative inverse of the matrix

trace() calculates the sum of diagonal elements

etc

In [30]:
# Example of Q42 (cont.)
# dot()    calculates product of two arrays (Al)
import numpy as np

arr17 = np.array([1, 3, 5])
arr18 = np.array([2, 4, 6])

# use of dot() to perform array multiplication
result = np.dot(arr17, arr18)

print(result)

44


In [31]:
# Example of Q42 (cont.)
# inner()   calculates inner product of arrays
import numpy as np

arr19 = np.array([[1, 3], 
                   [5, 7]])
arr20 = np.array([[2, 4], 
                   [6, 8]])

# inner() for 2D arrays
result = np.inner(arr19, arr20)

print(result)

[[14 30]
 [38 86]]


In [34]:
# Example of Q42 (cont.)
# trace()   calculates the sum of diagonal elements
import numpy as np

# define a 3x3 matrix
arr21 = np.array([[6, 3, 5], 
                   [9, 2, 1], 
                   [7, 8, 4]])

# compute the trace of the matrix
result = np.trace(arr21)

print(result)

12


### Q43: Give some examples of Numpy functions for performing statistical operations
#### Ans:


Numpy can perform linear algebric function such as,

median()	return the median of an array

mean()	return the mean of an array

std()	return the standard deviation of an array

percentile()	return the nth percentile of elements in an array

min()	return the minimum element of an array

max()	return the maximum element of an array

etc.

In [36]:
# Example of Q43 (cont.)

# median()   return the median of an array
import numpy as np

# create a 1D array with 5 elements
arr22 = np.array([1, 2, 3, 4, 7])
                                                                                                           
# calculate the median
median = np.median(arr22)

print(median) 

3.0


In [2]:
# Example of Q43 (cont.)

# mean() return the mean of an array

import numpy as np

# create a numpy array
marks = np.array([70, 74, 81, 67, 88])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)

76.0


In [4]:
# Example of Q43 (cont.)

#std() return the standard deviation of an array

import numpy as np

# create a numpy array
marks = np.array([77, 87, 91, 77, 89])
# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

6.013318551349163


### Q44: How do you find the right Numpy function for a specific operation or use case?
#### Ans:

1. Understand the problem:

It is essential to understand the problem this will help to determine what kind of function be needed.

2. Numpy Documentation:

The Numpy documentation is a great resource for finding the right function. It also provides a comprehensive list of functions, along with their parameters and examples of how to use them.

3. Search online:

There are many online resources available, including forums, blogs, and tutorials, where examples are present explaining  how to use Numpy functions for specific use cases.

4. Experiment:

Sometimes, the best way to find the right function is to do experiment with different functions and see which one works best for the specific case. 

5. Ask for help:

If there is still ambiguity in selecting the right function, a senior / expert could provide help and guide lines to select the right function and solve the problem.

### Q45: Where can you see a list of all the Numpy array functions and operations?
#### Ans:

With the help of dir() function we can find all list of 

In [10]:
import numpy as np

dir(np)
x=np.array(dir(np))
print (x)

['ALLOW_THREADS' 'AxisError' 'BUFSIZE' 'CLIP' 'ComplexWarning'
 'DataSource' 'ERR_CALL' 'ERR_DEFAULT' 'ERR_IGNORE' 'ERR_LOG' 'ERR_PRINT'
 'ERR_RAISE' 'ERR_WARN' 'FLOATING_POINT_SUPPORT' 'FPE_DIVIDEBYZERO'
 'FPE_INVALID' 'FPE_OVERFLOW' 'FPE_UNDERFLOW' 'False_' 'Inf' 'Infinity'
 'MAXDIMS' 'MAY_SHARE_BOUNDS' 'MAY_SHARE_EXACT' 'ModuleDeprecationWarning'
 'NAN' 'NINF' 'NZERO' 'NaN' 'PINF' 'PZERO' 'RAISE' 'RankWarning'
 'SHIFT_DIVIDEBYZERO' 'SHIFT_INVALID' 'SHIFT_OVERFLOW' 'SHIFT_UNDERFLOW'
 'ScalarType' 'Tester' 'TooHardError' 'True_' 'UFUNC_BUFSIZE_DEFAULT'
 'UFUNC_PYVALS_NAME' 'VisibleDeprecationWarning' 'WRAP' '_CopyMode'
 '_NoValue' '_UFUNC_API' '__NUMPY_SETUP__' '__all__' '__builtins__'
 '__cached__' '__config__' '__deprecated_attrs__' '__dir__' '__doc__'
 '__expired_functions__' '__file__' '__former_attrs__'
 '__future_scalars__' '__getattr__' '__git_version__' '__loader__'
 '__mkl_version__' '__name__' '__package__' '__path__' '__spec__'
 '__version__' '_add_newdoc_ufunc' '_builtins'

### Q46: What are the arithmetic operators supported by Numpy arrays? Illustrate with examples.
#### Ans:

Following are the arithmatic  operators supported by Numpy Arrays:


Addition	+	add()

Subtraction	-	subtract()

Multiplication	*	multiply()

Division	/	divide()

Exponentiation	**	power()

Modulus	%	mod()

In [11]:
# Example of Q46 (cont.)
# Addition + add() function in Numpy array 
import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print("Using the + operator:",result1) 

# using the add() function
result2 = np.add(first_array, second_array)
print("Using the add() function:",result2) 

Using the + operator: [ 3  7 11 15]
Using the add() function: [ 3  7 11 15]


In [12]:
# Example of Q46 (cont.)
# Subtraction - subtract() function in Numpy array

import numpy as np

first_array = np.array([3, 9, 27, 81])
second_array = np.array([2, 4, 8, 16])

# using the - operator
result1 = first_array - second_array
print("Using the - operator:",result1) 

# using the subtract() function
result2 = np.subtract(first_array, second_array)
print("Using the subtract() function:",result2) 

Using the - operator: [ 1  5 19 65]
Using the subtract() function: [ 1  5 19 65]


In [13]:
# Example of Q46 (cont.)
# Multiplication * multiply() function in Numpy array

import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the * operator
result1 = first_array * second_array
print("Using the * operator:",result1) 

# using the multiply() function
result2 = np.multiply(first_array, second_array)
print("Using the multiply() function:",result2) 

Using the * operator: [ 2 12 30 56]
Using the multiply() function: [ 2 12 30 56]


### Q47: What is array broadcasting? How is it useful? Illustrate with an example
#### Ans:


Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension. The arrays can be broadcast together if they are compatible with all dimensions.

numpy.broadcast() 



In [14]:
# Example of Q47
# an example of broadcasting is Vector Quantization

from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
argmin(dist)

0

### Q48:  Give some examples of arrays that are compatible for broadcasting?
#### Ans:

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when


they are equal, or

one of them is 1.

In [16]:
# Example of Q48
# an example of broadcasting
import numpy as np

v = np.array([1, 2, 3]) 
w = np.array([4, 5]) 

# To compute an outer product we first 
# reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output
# of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3, 1)) * w)

x = np.array([[1, 2, 3], [4, 5, 6]])

# x has shape 2x3 and v has shape (3,)
# so they broadcast to 2x3,
print(x + v)

# Add a vector to each column of a matrix X has
# shape 2x3 and w has shape (2, ) If we transpose X
# then it has shape 3x2 and can be broadcast against w 
# to yield a result of shape 3x2.

# Transposing this yields the final result 
# of shape 2x3 which is the matrix.
print((x.T + w).T)

# Another solution is to reshape w to be a column
# vector of shape 2X1 we can then broadcast it 
# directly against X to produce the same output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant, X has shape 2x3.
# Numpy treats scalars as arrays of shape(); 
# these can be broadcast together to shape 2x3.
print(x * 2)


[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


### Q49: Give some examples of arrays that are not compatible for broadcasting?
#### Ans:
Here are some examples of arrays that are not compatible for broadcasting:


- Arrays of different shapes;

           Array 1: Shape (3, 4)
   
           Array 2: Shape (2, 3)
           
  
  

- Arrays of different dimensions;

           Array 1: Shape (3, 4)

           Array 2: Shape (3, 1, 4)
           

   

- Arrays with different size;

           Array 1: Shape (3, 4)

           Array 2: Shape (3, 5)
   
etc.

### Q50: What are the comparison operators supported by Numpy arrays? Illustrate with examples.
#### Ans:

comparison operators in Numpy Arrays can compare the elements of two NumPy arrays.


- "<" (less than)	returns True if element of the first array is less than the second one

- "<=" (less than or equal to)	returns True if element of the first array is less than or equal to the second one

- ">" (greater than)	returns True if element of the first array is greater than the second one

- ">="   (greater than or equal to)	returns True if element of the first array is greater than or equal to the second one

- "==" (equal to)	returns True if the element of the first array is equal to the second one

- "!=" (not equal to)	returns True if the element of the first array is not equal to the second one

In [19]:
#example of Q50:

import numpy as np

arr23 = np.array([9, 12, 21])
arr24 = np.array([21, 12, 9])

# use of less()
result = np.less(arr23, arr24)
print("Using less():",result)    # Output: [ True False False]

# use of less_equal()
result = np.less_equal(arr23, arr24)
print("Using less_equal():",result)     # Output: [ True  True False]

# use of greater()
result = np.greater(arr23, arr24)
print("Using greater():",result)    # Output: [False False  True]

# use of greater_equal()
result = np.greater_equal(arr23, arr24)
print("Using greater_equal():",result)    # Output: [False  True  True]

# use of equal()
result = np.equal(arr23, arr24)
print("Using equal():",result)    # Output: [False  True False]

# use of not_equal()
result = np.not_equal(arr23, arr24)
print("Using not_equal():",result)    # Output: [ True False  True]

Using less(): [ True False False]
Using less_equal(): [ True  True False]
Using greater(): [False False  True]
Using greater_equal(): [False  True  True]
Using equal(): [False  True False]
Using not_equal(): [ True False  True]


### Q51: How do you access a specific subarray or slice from a Numpy array?
#### Ans:
Subarrays in an array can be accessed by using the slicing notation.

The slice of a Numpy array is done using the syntax below;

step=1, the start=0, and the stop= size of the array.

In [21]:
# example of Q51

arr25 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr25[0, 1, 2])

6


### Q52: Illustrate array indexing and slicing in multi-dimensional Numpy arrays with some examples.
#### Ans:

- Follwoing is a multidimentional array

arr26 = np.array([[[4,, 12, 13], [14, 25, 36]], [[47, 59, 49], [30, 40, 50]]])

Define the step, like this: [start:end:step]


In [31]:
# example of Q51
#Follwoing is a multidimentional array
arr26 = np.array([[[4, 12, 13], [14, 25, 36]], [[47, 59, 49], [30, 40, 50]]])

print(arr26[1, 1, 1])

40


### Q53:  How do you create a Numpy array with a given shape containing all zeros?
#### Ans:
To create a NumPy array with zeros the numpy.zeros() function is used which returns a new array of given shape and type, with zeros as shown in the example below;

In [34]:
#example of Q 53

import numpy as np

# creating 3D array
arr27 = np.zeros((3, 3, 3))

print(arr27)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### Q54:How do you create a Numpy array with a given shape containing all ones?
#### Ans:

With the help of numpy.ones numpy array(s) ould be created containing all ones as shown in the bleow example,


In [39]:
#example of Q 54
import numpy as np

arr28 = np.ones(3) # 1D array
print(arr28)
print()
arr29 = np.ones((2, 3)) #2D Array
print(arr29)



[1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]


### Q55: How do you create an identity matrix of a given shape?
#### Ans:

The function Numpy. identity() is used to creat identity matrix as described in steps below,

Step 1: Import numpy

Step 2: Take dimensions as input from the user

Step 3: Print the identity matrix using numpy.identity() function

Following is the example of identity matrix;

In [9]:
#example of Q 55
import numpy as np

dimension = int(3)
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [8]:
#example of Q 55 (Cont.)

import numpy as np

dimension = int(7)
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


### Q56: How do you create a random vector of a given length?
#### Ans:
An array of random integers can be generated using the randint() NumPy function.

This function takes three arguments, the lower end of the range, the upper end of the range, and the number of integer values to generate or the size of the array as shown in the following example;

In [14]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.04505134 0.25006462 0.76204536 0.88465134 0.38267104 0.10279787
 0.36632994 0.97155393 0.96999203 0.46507624]
Sorted array:
[0.04505134 0.10279787 0.25006462 0.36632994 0.38267104 0.46507624
 0.76204536 0.88465134 0.96999203 0.97155393]


### Q57: How do you create a Numpy array with a given shape with a fixed value for each element?
#### Ans:

To create a NumPy array with a given shape and a fixed value for each element, the numpy.full() function is used which takes the shape of array and desired value as an argument and returns  anew desired array.

eg
shape = (3, 4) and value = 5


In [19]:
# exapmple of Q 57

import numpy as np

shape = (4, 5)
value = 4

arr30 = np.full(shape, value)
print(arr30)

print()

shape = (2, 3)
value = 7
arr31 = (np.full(shape, value))
print (arr31)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]

[[7 7 7]
 [7 7 7]]


### Q58: How do you create a Numpy array with a given shape containing randomly initialized elements?
#### Ans:
To create a NumPy array with a given shape containing randomly initialized elements, the numpy.random module is used which provides several functions for generatingrandom numbers and arrays.

Example is given below;

In [27]:
# example of Q 58

import numpy as np

shape = (3, 4)

arr32 = np.random.random(shape)
print(arr32)

[[0.33104117 0.18391464 0.07363847 0.18483008]
 [0.74557129 0.14636224 0.80997263 0.14449633]
 [0.09781439 0.68257011 0.75941672 0.02175231]]


### Q59: What is the difference between np.random.rand and np.random.randn? Illustrate with examples.
#### Ans:

The main difference between np.random.rand and np.random.randn is the type of distribution they generate random numbers from.
np.random.rand`:
   - Generates random numbers from a uniform distribution between 0 and 1.
   - Takes the shape of the desired output as arguments.
   - All generated numbers are equally likely to occur.
   - Example:

Examples are given below;

In [28]:
# example of Q 59 (cont.)

#    np.random.rand generates random numbers from a uniform distribution between 0 and 1. it takes the shape of the desired output as arguments.
#    all generated numbers are equally likely to occur.
  
import numpy as np

shape = (3, 4)

arr33 = np.random.rand(*shape)
print(arr33)

[[0.29250228 0.80400204 0.92930254 0.36900915]
 [0.61582514 0.31761466 0.11942399 0.74021377]
 [0.17690172 0.55322603 0.10618323 0.28556484]]


In [29]:
# example of Q 59 (cont.)

# np.random.randn generates random numbers from a standard normal distribution (mean 0, standard deviation 1). It Takes
# the shape of the desired output as arguments. The generated numbers follow a bell-shaped curve around the mean of 0.
  
import numpy as np

shape = (3, 4)

arr34 = np.random.randn(*shape)
print(arr34)

[[ 1.61157468  0.77790533  0.82777994 -2.11214387]
 [ 0.35383385  0.97153652  2.16832282  0.506048  ]
 [-1.17815652  1.13310982 -0.88527851  0.25839672]]


### Q60: What is the difference between np.arange and np.linspace? Illustrate with examples.
#### Ans:

The main differrence between np.arange and np.linspace is as follows;

1- arange allows you to specify the size of the steps

2- linspace allows you to specify the number of steps

Furthe ilustration and example s are given below;

In [34]:
# example of Q 60 (cont.)

# np.arange generates a sequence of numbers with a specified start, stop, and step size. It takes the start, 
# stop, and step size as arguments. The generated sequence includes the start value but excludes the stop value.

import numpy as np

start = 0
stop = 10
step = 2

arr35 = np.arange(start, stop, step)
print(arr35)


[0 2 4 6 8]


In [35]:
# example of Q 60 (cont.)

# np.linspace generates a sequence of numbers with a specified start, stop, and number of elements. It takes the start,
# stop, and the number of elements as arguments. The generated sequence includes both the start and stop values.
  
import numpy as np

start = 0
stop = 10
num_elements = 5

arr36 = np.linspace(start, stop, num_elements)
print(arr36)

[ 0.   2.5  5.   7.5 10. ]


# Other Questions (Quiz)


### Quiz 1:  Import the numpy package under the name np

In [1]:
import numpy as np 

#(np is the alias of Numpy)

### Quiz 2: Print the numpy version and the configuration 

In [8]:
import numpy as np

#(to show the version of Numpy library installed)
np.__version__

'1.24.3'

In [10]:
# Quiz 2 continued

#(to show the configuration of installed Numpy library )
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mubeen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mubeen/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mubeen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mubeen/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mubeen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mubeen/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mubeen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mubeen/anacon

### Quiz 3: Create a null vector of size 10 

In [20]:
import numpy as np

null_vector  = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Quiz 4: How to find the memory size of any array ?

In [21]:
# size and itemsize attributes will be used to find out the memory size of a numpy array
import numpy as np

# create a numpy 1d-array
array1 = np.array([10,20,30])

print("Size of the array: ", array1.size)

print("Memory size of one array element in bytes: ",array1.itemsize)

# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:", array1.size * array1.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  4
Memory size of numpy array in bytes: 12


### Quiz 5: How to get the documentation of the numpy add function from the command line? 

In [19]:
print(np.info(np. add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### Quiz 6:  Create a null vector of size 10 but the fifth value which is 1 

In [3]:
import numpy as np

null_vector = np.zeros(10)

# fifth value will be on index 4 therefore,

null_vector [4]= 1

print (null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Quiz 7: Create a vector with values ranging from 10 to 49

In [9]:
import numpy as np

vector1 = np.arange(10, 49)

print ("vector1: ", (vector1))

vector1:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### Quiz 8: Reverse a vector (first element becomes last) 

In [24]:
import numpy as np

vector2 = np.arange(11, 30)
rev_vector = vector2[::-1]
print ("Original vector: ", (vector2))
print()
print ("Reverse Vector:  ", (rev_vector))

Original vector:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]

Reverse Vector:   [29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11]


### Quiz 9: Create a 3x3 matrix with values ranging from 0 to 8 

In [57]:
#Can not reshape array of size 8 into shape (3,3). Range should be 0 to 9 for matrix shape of 3 x 3

import numpy as np

matrix1 = np.arange(0, 8). reshape (3, 3)

print(matrix1)


ValueError: cannot reshape array of size 8 into shape (3,3)

### Quiz 10: Find indices of non-zero elements from [1,2,0,0,4,0]  

In [54]:
import numpy as np

array2 = np.array([1, 2, 0, 0, 4, 0]) 

print ("Input array :" , (array2)) 

indices = np.nonzero(array2) 

print ("Indices of non zero elements : ", indices) 

Input array : [1 2 0 0 4 0]
Indices of non zero elements :  (array([0, 1, 4], dtype=int64),)


### Quiz 11: Create a 3x3 identity matrix 

In [61]:
import numpy as np
matrix2 = np.identity(3)
print (matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Quiz 12: Create a 3x3x3 array with random values 

In [65]:
import numpy as np
array3 = np.random.random ((3, 3, 3))
print (array3)

[[[0.48214679 0.93776735 0.99166851]
  [0.57406982 0.60187977 0.07788664]
  [0.21917324 0.67163278 0.81697867]]

 [[0.39008683 0.69958762 0.4957395 ]
  [0.40909946 0.81248078 0.19529959]
  [0.87299866 0.24452431 0.45853045]]

 [[0.21630064 0.9920064  0.9648964 ]
  [0.96132142 0.69710235 0.29066573]
  [0.77217938 0.65115359 0.70014627]]]


### Quiz 13: Create a 10x10 array with random values and find the minimum and maximum values 

In [12]:
import numpy as np
array3 = np.random.random([10,10])
print("Original Array: " )
print(array3)
print()
minimum, maximum = array3.min(), array3.max()
print("Minimum value & Maximum Value")
print(minimum, maximum)

Original Array: 
[[0.36723193 0.00242679 0.42793981 0.76057119 0.61773567 0.98939973
  0.07206437 0.55003713 0.881906   0.47249193]
 [0.67549263 0.7630147  0.59314973 0.52308432 0.69047328 0.95132903
  0.5055044  0.93839079 0.87468307 0.17087217]
 [0.19191169 0.19020075 0.82984946 0.48464603 0.81245471 0.96020455
  0.83787348 0.9706474  0.04763088 0.12569336]
 [0.52312522 0.04243202 0.87778704 0.39023973 0.97827367 0.92976294
  0.33321228 0.11643356 0.49338648 0.20910687]
 [0.37572384 0.53630133 0.11570356 0.46915547 0.28454265 0.8923324
  0.6360535  0.23950695 0.38807026 0.10562587]
 [0.006855   0.25212761 0.0740757  0.2371244  0.66566931 0.73753286
  0.05992966 0.17605992 0.22726609 0.47815664]
 [0.66052397 0.4215799  0.82595209 0.26795978 0.25215722 0.59525849
  0.47843982 0.36817566 0.42887469 0.29230623]
 [0.72287545 0.65652992 0.06904537 0.02522004 0.2896668  0.51180451
  0.44620163 0.83142649 0.6776593  0.26707299]
 [0.3047672  0.12271816 0.65568493 0.51169587 0.41361537 0.57320

### Quiz 14: Create a random vector of size 30 and find the mean value 

In [16]:
import numpy as np
vector3 = np.random.random(30)
mean= vector3.mean()
print ("Original Vector")
print (vector3)
print("Mean Value")
print (mean)

Original Vector
[5.72134758e-01 1.08877022e-01 7.90060476e-04 4.00729069e-01
 3.27816035e-01 9.68843289e-01 5.40951901e-01 4.82314947e-01
 9.04768442e-01 5.04130562e-01 3.83194500e-01 1.63395946e-01
 6.51332351e-02 3.55413248e-01 4.31697866e-01 2.36276954e-02
 4.68391203e-01 3.54660402e-01 3.32528520e-01 1.66498669e-01
 5.21421723e-01 1.15482735e-01 4.11345143e-01 2.43603925e-01
 5.62317286e-01 1.85814052e-01 5.66028961e-02 7.25529503e-01
 3.46841726e-01 1.93557327e-01]
Mean Value
0.3639471228188897


### Quiz 15: Create a 2d array with 1 on the border and 0 inside 

In [25]:
import numpy as np

array4 = np.ones([5, 5])
array4[1:-1, 1:-1]=0
print (array4)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Quiz 16: How to add a border (filled with 0's) around an existing array?

In [46]:
import numpy as np
array5 = np.ones([6,6])
array5 = np.pad(array5, pad_width=1, constant_values=0)
print(array5)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


### Quiz17: What is the result of the following expression?
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [60]:
import numpy as np
a = 0*np.nan
print ("Result of the expression 0*np.nan = ", (0*np.nan))
print ("Result of the expression np.nan == np.nan = ", (np.nan==np.nan))
print ("Result of the expression np.inf > np.nan = ", (np.inf > np.nan))    
print ("Result of the expression np.nan - np.nan = ", (np.nan - np.nan))
print ("Result of the expression np.nan in set([np.nan]) = ", (np.nan in set([np.nan])))
print ("Result of the expression 0.3 == 3 * 0.1 = ", (0.3 == 3 * 0.1))

Result of the expression 0*np.nan =  nan
Result of the expression np.nan == np.nan =  False
Result of the expression np.inf > np.nan =  False
Result of the expression np.nan - np.nan =  nan
Result of the expression np.nan in set([np.nan]) =  True
Result of the expression 0.3 == 3 * 0.1 =  False


### Quiz 18: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [64]:
import numpy as np
matrix3 = np.diag(1+np.arange(4),k=-1)
print (matrix3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Quiz 19: Create a 8x8 matrix and fill it with a checkerboard pattern

In [70]:
import numpy as np
matrix4 = np.zeros((8,8),dtype=int)
matrix4[1::2,::2] = 1
matrix4[::2,1::2] = 1
print(matrix4)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Quiz 20: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [75]:
#This quiz requires unravel_index() function to solve as per following parameters;
#numpy.unravel_index(indices, shape, order='C')
#Converts a flat index or array of flat indices into a tuple of coordinate arrays.
import numpy as np
array5 = np.unravel_index(100,(6,7,8))
print (array5)


(1, 5, 4)


### Quiz 21: Create a checkerboard 8x8 matrix using the tile function 

In [80]:
import numpy as np

matrix5 = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(matrix5)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Quiz 22: Normalize a 5x5 random matrix 

In [88]:
import numpy as np
# create a 5x5 array with random values
array6 = np.random.rand(5, 5)
print("\n Original array elements :",)
print(array6)
# compute the mean of each column
col_means = np.mean(array6, axis=0)
# normalize each column by subtracting its mean and dividing by its standard deviation
arr_normalized = (array6 - col_means) / np.std(array6, axis=0)
print("\n Original Array :")
print (array6)
print("\n Normalized Array (column-wise) :")
print(arr_normalized)


 Original array elements :
[[0.82170162 0.57391666 0.10288877 0.3209065  0.07093291]
 [0.87533005 0.93018268 0.30794689 0.84330363 0.17054214]
 [0.37173545 0.24228127 0.37222802 0.55993995 0.38776684]
 [0.78720874 0.34757338 0.45862874 0.75377755 0.64466593]
 [0.55364683 0.43673366 0.24683053 0.6911599  0.17611689]]

 Original Array :
[[0.82170162 0.57391666 0.10288877 0.3209065  0.07093291]
 [0.87533005 0.93018268 0.30794689 0.84330363 0.17054214]
 [0.37173545 0.24228127 0.37222802 0.55993995 0.38776684]
 [0.78720874 0.34757338 0.45862874 0.75377755 0.64466593]
 [0.55364683 0.43673366 0.24683053 0.6911599  0.17611689]]

 Normalized Array (column-wise) :
[[ 0.73526054  0.28440095 -1.62237717 -1.72286201 -1.06749853]
 [ 1.01735878  1.77929179  0.08529527  1.15341318 -0.58212071]
 [-1.63166803 -1.10713984  0.6206124  -0.40676371  0.47637609]
 [ 0.55381983 -0.66533455  1.34013585  0.66049007  1.72819909]
 [-0.67477112 -0.29121836 -0.42366635  0.31572247 -0.55495594]]


### Quiz 23: Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [97]:
import numpy as np
# Define the custom dtype for RGBA colors
datatype = datatype_rgba = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])
# Create a Numpy array of RGBA colors using the custom dtype
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=datatype_rgba)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


### Quiz 24:  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [101]:
import numpy as np
matrix6 = np.random.random((5,3))
print("\n First array:")
print(matrix6)
matrix7 = np.random.random((3,2))
print("\n Second array:")
print(matrix7)
matrix8 = np.dot(matrix6, matrix7)
print("\n Dot product of two arrays:")
print(matrix8)


 First array:
[[0.76443967 0.51089847 0.84553915]
 [0.36687004 0.04842627 0.91320925]
 [0.49236685 0.07876351 0.42509524]
 [0.09382993 0.02950711 0.72880397]
 [0.34737926 0.14273403 0.48575429]]

 Second array:
[[0.52334042 0.96915099]
 [0.49144719 0.6209047 ]
 [0.24410745 0.48519572]]

 Dot product of two arrays:
[[0.8575442  1.46832871]
 [0.43871806 0.82870578]
 [0.40015249 0.73233684]
 [0.24151266 0.46286904]
 [0.37052009 0.66097309]]


### Quiz 25: Given a 1D array, negate all elements which are between 3 and 8, in place 

In [103]:
import numpy as np
array6 = np.arange(11)
array6[(3 < array6) & (array6 <= 8)] *= -1
array6[array6 > 5]
array6 = np.arange(11)
array6[(3 < array6) & (array6 <= 8)] *= -1
array6[array6 > 5]

array([ 9, 10])

# Quiz 26: What is the output of the following script?

print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

##### print(sum(range(5),-1)) = 9

##### from numpy import *

##### print(sum(range(5),-1)) =10

### Quiz 27: Consider an integer vector Z, which of these expressions are legal? 

In [141]:
import numpy as np
Z = np.arange(3)
print ("Z = (Z**Z) =  ", (Z))
print ("\n 2 << Z >> 2) = ", (2 << Z >> 2))
print ("\n Z < - Z) = ", (Z < - Z)) 
print ("\n 1j * Z) = ", (1j * Z))
print ("\n Z / 1 / 1) = ", (Z / 1 / 1))

print ("\n Z < Z > Z) = ", (Z < Z > Z)) # ValueError Traceback (most recent call last) Cell In[141], line 8
                        # The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Z = (Z**Z) =   [0 1 2]

 2 << Z >> 2) =  [0 1 2]

 Z < - Z) =  [False False False]

 1j * Z) =  [0.+0.j 0.+1.j 0.+2.j]

 Z / 1 / 1) =  [0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Quiz 28: What are the result of the following expressions? 

np.array(0) / np.array(0)  
Ans: nan

np.array(0) // np.array(0)     
Ans: 0

np.array([np.nan]).astype(int).astype(float)      
Ans: [-2.14748365e+09]

In [396]:
import numpy as np
x = np.array(0) / np.array(0) 
print(x)

nan


In [397]:
import numpy as np
x = np.array(0) // np.array(0) 
print(x)

0


In [398]:
import numpy as np
x= np.array([np.nan]).astype(int).astype(float)
print (x)

[-2.14748365e+09]


###  29: How to round away from zero a float array

In [163]:
#To round away from zero a float array in NumPy, you can use the `numpy.ceil()` and `numpy.floor()` functions.

#Here's an example code snippet in Python:

import numpy as np

float_array = np.array([1.2, -2.5, 3.7, -4.9])

rounded_array = np.where(float_array > 0, np.ceil(float_array), np.floor(float_array))

print("rounded_array = ", (rounded_array))


rounded_array =  [ 2. -3.  4. -5.]


### Quiz 30:  How to find common values between two arrays?

In [165]:
import numpy as np 

array7 = np.array([0, 1, 2, 3, 4]) 
array8 = [1, 3, 4] 

# Common values between two arrays 
print("Common Values in two arrays are: ", (np.intersect1d(array7, array8))) 


Common Values in two arrays are:  [1 3 4]


### Quiz 31: How to ignore all numpy warnings (not recommended)? 

In [180]:
# numpy.seterr(all=None, divide=None, over=None, under=None, invalid=None)
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

### Quiz 32 : Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)

In [181]:
import numpy as np
x = np.sqrt(-1) == np.emath.sqrt(-1)
print (x)

False


### Quiz 33: How to get the dates of yesterday, today and tomorrow?

In [195]:
import numpy as np
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D') 
print ("Today Date is: ", (today))
print ("Yesterday Date was: ", (yesterday))
print ("Tomorrow Date will be: ", (tomorrow))


Today Date is:  2023-11-05
Yesterday Date was:  2023-11-04
Tomorrow Date will be:  2023-11-06


### Quiz 34: How to get all the dates corresponding to the month of July 2016? 

In [199]:
import numpy as np
print("Jul, 2016 \n")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

Jul, 2016 

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### Quiz 35: How to compute ((A+B)*(-A/2)) in place (without copy) 

In [200]:
import numpy as np

A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

### Quiz 36: Extract the integer part of a random array of positive numbers using 4 different methods 

In [235]:
import numpy as np
x = np.random.uniform(0,10,10)

print('Method 1: x=',x)
print ('\n Method 2: x=' ,x-x%1)
print ('\n Method 3: x= ' ,np.floor(x))
print ('\n Method 4: x=' ,x.astype(int))

Method 1: x= [7.39567041 0.50477672 9.17398702 0.44370156 0.01663713 9.77664191
 1.27928774 8.0102734  5.09306648 4.6976366 ]

 Method 2: x= [7. 0. 9. 0. 0. 9. 1. 8. 5. 4.]

 Method 3: x=  [7. 0. 9. 0. 0. 9. 1. 8. 5. 4.]

 Method 4: x= [7 0 9 0 0 9 1 8 5 4]


### Quiz 37: Create a 5x5 matrix with row values ranging from 0 to 4 

In [238]:
import numpy as np
matrix9 = np.zeros((5,5))
print("Original array:" , (matrix9))

print("Row values ranging from 0 to 4.")
matrix9 += np.arange(5)
print(matrix9)

Original array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### Quiz 38: Consider a generator function that generates 10 integers and use it to build an array

In [244]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

### Quiz 39: Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [245]:
import numpy as np
vector2 = np.linspace(0,1,12,endpoint=True)[1:-1]
print(vector2)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### Quiz 40:  Create a random vector of size 10 and sort it

In [249]:
import numpy as np
vector3 = np.random.random(10)
print("Original array: \n ", (vector3))

vector3.sort()
print("\n Sorted array: \n", (vector3))


Original array: 
  [0.78349006 0.3096257  0.96238133 0.19394706 0.43598964 0.21572406
 0.58985231 0.58897112 0.18331582 0.36131723]

 Sorted array: 
 [0.18331582 0.19394706 0.21572406 0.3096257  0.36131723 0.43598964
 0.58897112 0.58985231 0.78349006 0.96238133]


### Quiz 41: How to sum a small array faster than np.sum? 

In [251]:
import time
begin_time = time.time()
array10 = np.arange(1000000)
np.sum(array10)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
array10 = np.arange(1000000)
np.add.reduce(array10)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

3.995180130004883
4.000425338745117


### Quiz 42: Consider two random array A and B, check if they are equal

In [252]:
import numpy as np
array11 = np.random.randint(0,2,6)
print("First array:", (array11))
array12 = np.random.randint(0,2,6)
print("Second array:", (array12))
print("Test above two arrays are equal or not!")
array_equal = np.allclose(array11, array12)
print(array_equal)

First array: [1 0 1 1 1 0]
Second array: [0 0 0 0 0 1]
Test above two arrays are equal or not!
False


### Quiz 43: Make an array immutable (read-only) 

In [254]:
array13 = np.zeros(10)
x.flags.writeable = False
array13[1] = 1   # ValueError: assignment destination is read-only
print("Read Only Array: ", (array13))

Read Only Array:  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


### Quiz 44: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [256]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
R = np.sqrt(x ** 2 + y ** 2)
T = np.arctan2(y, x)
print(R)
print(T)

[0.92173735 0.95989679 0.35074401 1.06318199 0.19779621 0.26131632
 0.6725045  0.83910874 0.61062873 0.38311656]
[0.37872187 1.54010431 0.72957061 0.90215447 0.73925037 0.91613138
 1.33877018 0.72683152 0.01776948 0.36933469]


### Quiz 45: Create random vector of size 10 and replace the maximum value by 0 

In [258]:
import numpy as np
vector4 = np.random.random(10)
print("Original array:", (vector4))
vector4[vector4.argmax()] = 0
print("Maximum value replaced by 0:", print (vector4))

Original array: [0.76520657 0.93909525 0.15548761 0.39242872 0.48947476 0.85758369
 0.05963644 0.48757708 0.82976693 0.52296234]
[0.76520657 0.         0.15548761 0.39242872 0.48947476 0.85758369
 0.05963644 0.48757708 0.82976693 0.52296234]
Maximum value replaced by 0: None


### Quiz 46: Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

In [261]:
import numpy as np
array14 = np.zeros((5, 5), [('x', float), ('y', float)])
array14['x'], array14['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(array14)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### Quiz 47: Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [263]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
cm = 1 / (x - y)
cm = 1 / np.subtract.outer(x, y)
np.linalg.det(cm)

array([[-8.29428660e+06, -7.66855773e+05,  1.06125319e+05,
        -1.38374082e+04, -1.46439109e+06],
       [ 1.43138936e+03,  1.56456673e+06,  1.05086046e+05,
        -1.96243029e+06, -1.38899595e+06],
       [-2.29030046e+04,  8.83742987e+02, -3.52432395e+04,
        -1.15288477e+05,  1.38107265e+08],
       [ 7.35020516e+05, -1.79809384e+04, -1.68014463e+07,
         2.12728004e+06,  2.44847621e+05],
       [ 8.52732941e+02,  4.96787022e+07,  2.44250110e+08,
        -1.42751396e+06,  2.05302015e+06]])

### Quiz 48: Print the minimum and maximum representable value for each numpy scalar type 

Here are the minimum and maximum representable values for each numpy scalar type:

bool: minimum = False, maximum = True
int8: minimum = -128, maximum = 127
uint8: minimum = 0, maximum = 255
int16: minimum = -32768, maximum = 32767
uint16: minimum = 0, maximum = 65535
int32: minimum = -2147483648, maximum = 2147483647
uint32: minimum = 0, maximum = 4294967295
int64: minimum = -9223372036854775808, maximum = 9223372036854775807
uint64: minimum = 0, maximum = 18446744073709551615
float16: minimum = -65504.0, maximum = 65504.0
float32: minimum = -3.4028235e+38, maximum = 3.4028235e+38
float64: minimum = -1.7976931348623157e+308, maximum = 1.7976931348623157e+308
complex64: minimum = (-3.4028235e+38-3.4028235e+38j), maximum = (3.4028235e+38+3.4028235e+38j)
complex128: minimum = (-1.7976931348623157e+308-1.7976931348623157e+308j), maximum = (1.7976931348623157e+308+1.7976931348623157e+308j)

Note that the minimum and maximum values for floating point types are not exact due to the limitations of floating point arithmetic.

### Quiz 49: How to print all the values of an array?

In [270]:
#To print all the values of an array in Python, you can use a loop to iterate over each element and print it.

import numpy as np

# Create an example array
array14 = np.array([1, 2, 3, 4, 5])

# Print all the values of the array
for value in array14:
    print(value)

1
2
3
4
5


### Quiz 50: How to find the closest value (to a given scalar) in a vector? 

In [272]:
import numpy as np
array15 = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(array15-a)).argmin()
print(array15[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
35.629006705303354
36


### Quiz 51:  Create a structured array representing a position (x,y) and a color (r,g,b) 

In [279]:
#To create a structured array representing a position (x, y) and 
#a color (r, g, b), you can use the `numpy.dtype` 
#function to define the data types and names for each field. Here's an example:

import numpy as np

# Define the data types and names for each field
dtype = np.dtype([('position', [('x', float), ('y', float)]),
                 ('color', [('r', int), ('g', int), ('b', int)])])

# Create an example structured array
array16 = np.array([((1.0, 2.0), (255, 0, 0)),
                ((3.5, 4.5), (0, 255, 0)),
                ((6.0, 7.0), (0, 0, 255))], dtype=dtype)

# Print the structured array
print(array16)

[((1. , 2. ), (255,   0,   0)) ((3.5, 4.5), (  0, 255,   0))
 ((6. , 7. ), (  0,   0, 255))]


### Quiz 52: Consider a random vector with shape (100, 2) representing coordinates, find point by point distances 

In [283]:
import numpy as np

from scipy.spatial.distance import cdist

# Create an example random vector with shape (100,2)
coords = np.random.rand(100, 2)

# Calculate the pairwise distances between all points
distances = cdist(coords, coords)

import numpy as np

# Create an example random vector with shape (100,2)
coords = np.random.rand(100, 2)

# Calculate the pairwise distances between adjacent points
deltas = np.diff(coords, axis=0)
distances = np.linalg.norm(deltas, axis=1)

# Print the resulting distances array
print(distances)

[0.33253447 0.43287151 0.79731931 0.40524766 0.57151385 0.7548722
 0.27702423 0.60591162 0.83026401 0.82931894 0.64789693 0.3160286
 0.3428311  0.50251525 0.45486016 0.51536583 0.52004615 0.6951081
 0.5503586  0.2394057  0.33728177 0.49308437 0.04171154 0.44744392
 0.39846554 0.48247953 0.09477425 0.9045143  0.50519166 0.72559242
 0.30339761 0.5342774  0.50698951 0.41611168 0.30671623 0.54067322
 0.33425161 0.67665228 0.67548487 0.3835762  0.62264175 0.74088137
 0.45058945 0.40784332 0.82092251 0.2023214  0.50650689 0.28451526
 0.88970485 0.69106797 0.43865971 0.39732254 0.21883899 0.57198363
 0.58325565 0.62901004 0.8570607  0.81334843 0.80642954 0.5401138
 0.59672513 0.58727691 0.35300928 0.19759603 0.36271722 0.64889216
 0.35433215 0.34018656 0.6303254  0.43983888 0.06967555 0.46691008
 0.18336031 0.20638381 0.34632066 0.81026086 0.19674054 0.72391867
 0.23137819 0.65568826 0.51331313 0.23689162 0.16212674 0.65966816
 0.58737407 0.72981948 0.27998007 0.32848628 0.68879001 0.46497588

### Quiz 53: How to convert a float (32 bits) array into an integer (32 bits) in place?

In [287]:
from numpy  import *

float_data_list = [1.2, 3.5, 5.1]

matrice = array(float_data_list, dtype ='int32' ) # define dtype
print (matrice)

[1 3 5]


### Quiz 54: How to read the following file?

1, 2, 3, 4, 5

6,  ,  , 7, 8

 ,  , 9,10,11 
 
 
 It will be read as follows
 
 [[ 1.  2.  3.  4.  5.]
 
 [ 6. nan nan  7.  8.]
 
 [nan nan  9. 10. 11.]]

### Quiz 55: What is the equivalent of enumerate for numpy arrays? 

In [297]:
array17 = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array17):
    print(index, value)
for index in np.ndindex(array17.shape):
    print(index, array17[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### Quiz 56:  Generate a generic 2D Gaussian-like array 

In [298]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### Quiz 57: How to randomly place p elements in a 2D array?  

In [300]:
import numpy as np
n = 10
p = 3
array18 = np.zeros((n,n))
np.put(array18, np.random.choice(range(n*n), p, replace=False),1)
print(array18)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


### Quiz 58: Subtract the mean of each row of a matrix 

In [304]:
import numpy as np
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[-0.41790352  0.39098263 -0.29392489 -0.32388686 -0.18288209  0.16523552
   0.02369946  0.18343993  0.17972692  0.27551291]
 [ 0.28182002 -0.30443237 -0.30271376 -0.48359588  0.22649599 -0.07416779
   0.20410501  0.29134384  0.29808116 -0.13693622]
 [ 0.06511669 -0.36412485  0.1014824   0.072855    0.37135894 -0.08134384
  -0.43193971  0.06727797  0.44793041 -0.24861301]
 [-0.35595281  0.40170946  0.37236952 -0.43490692  0.31594964 -0.17576696
  -0.26389217  0.21967911 -0.30759035  0.22840149]
 [ 0.20824944  0.12218819 -0.27468383 -0.29960233 -0.08982748  0.10001923
   0.04848351  0.00466818 -0.0392642   0.2197693 ]]


### Quiz 59: How to sort an array by the nth column? 

In [305]:
import numpy as np
array19 = np.random.randint(0,10,(3,3))
print(array19)
print(array19[array19[:,1].argsort()])

[[3 0 6]
 [2 0 6]
 [6 4 8]]
[[3 0 6]
 [2 0 6]
 [6 4 8]]


### Quiz 60: How to tell if a given 2D array has null columns?

In [307]:
import numpy as np

array20 = np.random.randint(0,3,(3,10))
print((~array20.any(axis=0)).any())

# null : np.nan
array20=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(array20).all(axis=0))

True
[False False  True]


### Quiz 61: Find the nearest value from a given value in an array 

In [308]:
import numpy as np

array21 = np.random.uniform(0,1,10)
n = 0.5
m = array21.flat[np.abs(array21 - n).argmin()]
print(m)

0.5690794196056335


### Quiz 62: Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [309]:
import numpy as np
array22 = np.arange(3).reshape(3,1)
array23 = np.arange(3).reshape(1,3)
it = np.nditer([array22, array23, None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### Quiz 63: Create an array class that has a name attribute 

In [317]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', None)

# Create an example NamedArray
array24 = NamedArray([1, 2, 3, 4, 5], name='MyArray')

# Access the name attribute
print(array24. name)


MyArray


### Quiz 64: Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [318]:
import numpy as np
vector5 = np.ones(10)
I = np.random.randint(0,len(vector5),20)
Z += np.bincount(I, minlength=len(vector5))
print(vector5)
np.add.at(vector5, I, 1)
print(vector5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3. 3. 4. 4. 5. 2. 3. 3. 2. 1.]


### Quiz 65: How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 

In [319]:
import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### Quiz 66: Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

In [321]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

n = len(np.unique(I24))
print(n)

64
64


### Quiz 67: Considering a four dimensions array, how to get sum over the last two axis at once 

In [322]:
import numpy as np
array25 = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = array25.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = array25.reshape(array25.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[38 74 58 50]
 [51 59 56 54]
 [57 40 55 49]]
[[38 74 58 50]
 [51 59 56 54]
 [57 40 55 49]]


### Quiz 68: Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [324]:
import numpy as np
import pandas as pd

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

print(pd.Series(D).groupby(S).mean())

[0.45273176 0.35419173 0.57587125 0.5178094  0.47457242 0.61590684
 0.30564429 0.5484933  0.59811248 0.58108665]
0    0.452732
1    0.354192
2    0.575871
3    0.517809
4    0.474572
5    0.615907
6    0.305644
7    0.548493
8    0.598112
9    0.581087
dtype: float64


### Quiz 69: How to get the diagonal of a dot product?

In [335]:
import numpy as np

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.82872807, 1.19974471, 0.27808441, 1.06043833, 0.8772623 ])

### Quiz 70: Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [336]:
import numpy as np
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### Quiz 71: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [337]:
import numpy as np
array26 = np.ones((5,5,3))
array27 = 2*np.ones((5,5))
print(array26 * array27[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### Quiz 72: How to swap two rows of an array? 

In [340]:
import numpy as np
array28 = np.arange(25).reshape(5,5)
array28[[0,1]] = array28[[1,0]]
print(array28)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Quiz 73: Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles 

In [341]:
import numpy as np
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  4) ( 0, 24) ( 4, 24) (13, 84) (13, 88) (18, 39) (18, 61) (18, 64)
 (18, 98) (33, 36) (33, 74) (35, 83) (35, 85) (36, 74) (37, 42) (37, 85)
 (39, 98) (42, 85) (45, 62) (45, 98) (61, 64) (62, 98) (64, 81) (64, 97)
 (68, 90) (68, 98) (81, 97) (83, 85) (84, 88) (90, 98)]


### Quiz 74: Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? 

In [342]:
import numpy as np
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


### Quiz 75: How to compute averages using a sliding window over an array? 

In [343]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
array29 = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

array29 = np.arange(20)
print(sliding_window_view(array29, window_shape=3).mean(axis=-1))


[2. 3. 4.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### Quiz 76: Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [344]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### Quiz 77: How to negate a boolean, or to change the sign of a float inplace? 

In [345]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.36662506,  0.46117117,  0.17674238,  0.01840489, -0.88349412,
       -0.39718989,  0.08967133, -0.15646221, -0.03479724, -0.77414631,
        0.49412452,  0.72738168,  0.46095952, -0.85191135,  0.1814234 ,
        0.10120001,  0.90274322, -0.72969906,  0.26498992, -0.70580905,
       -0.19658044, -0.30555221,  0.42583936, -0.33691762, -0.6198395 ,
       -0.76043991,  0.55874269, -0.64709582, -0.15750502, -0.47025267,
        0.7845259 ,  0.93246218, -0.23728018,  0.05220111,  0.3184704 ,
       -0.97943022, -0.52952828,  0.64941383, -0.40372335, -0.37848146,
        0.39805462, -0.17867912,  0.57018675, -0.23882137, -0.38864866,
       -0.09542671,  0.57405908,  0.09741601, -0.08091588,  0.91337653,
       -0.53302195, -0.49878183,  0.39517443,  0.89421489,  0.14456346,
       -0.07999518, -0.16859701,  0.9135971 , -0.72982442, -0.26079605,
        0.41185387,  0.18048439,  0.17472156,  0.57527895,  0.42806216,
       -0.05624081, -0.22727829,  0.47655947, -0.75615257,  0.44

### Quiz 78: Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 

In [346]:
import numpy as np
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.40161446  2.20333549  9.99185694 14.02831102  5.93452456  7.84616071
  9.94401762 10.42001932  6.61853884  7.34813925]


### Quiz 79: Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 

In [347]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.93816434  1.83619223  4.03012754  3.78092235  7.08644625  8.45072165
   2.65363429  1.20591059  0.68843196  3.5583797 ]
 [10.19642524  5.87766161  1.29945515  1.80762247  1.81665916  0.77060559
   2.11197847  6.38300984  0.39577966  5.3324091 ]
 [ 7.75998654  5.86121286  4.5112066   6.19078352 12.34819395 12.44761405
   4.48837907  6.41270048  0.35454797  9.01818009]
 [ 6.49316813  8.54915112 18.1695877  14.95354455  7.15416747 15.26549415
  14.9263366   7.73201668 15.84617911  1.06673925]
 [ 6.3248651   7.47129776  5.99058431  7.84502999 13.61274641 14.06079813
   6.11127236  6.79513192  0.85870385 10.08312419]
 [13.6652482   8.48443604  2.17643321  5.06555302  3.15839134  1.85323809
   5.48601352  5.57424414  2.93772698  6.1168134 ]
 [ 5.82890775  0.21412664  5.89432194  3.91361518  3.62226394  6.86294173
   3.33586409  3.61165319  3.71618271  0.43152652]
 [ 8.43838085  0.05788942  3.41085263  2.43616843  4.86690919  6.56549526
   1.51885421  0.72517258  0.68146837  1.33076889]


### Quiz 80: Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) 

In [350]:
import numpy as np
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

print(Z)
print(R)

[[7 3 1 0 9 8 7 1 3 6]
 [1 0 0 5 4 4 2 3 5 8]
 [3 3 0 9 2 3 6 3 0 5]
 [1 2 1 7 8 5 5 9 3 6]
 [1 1 9 7 7 5 2 6 1 0]
 [3 5 7 9 6 8 2 2 0 1]
 [5 0 3 8 5 6 6 7 3 7]
 [7 5 6 0 2 2 4 3 8 4]
 [0 6 5 8 3 4 0 0 9 2]
 [0 0 3 4 7 5 7 2 7 4]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Quiz 81: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [351]:
import numpy as np
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### Quiz 82: Compute a matrix rank 

In [352]:
import numpy as np
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


### Quiz 83: How to find the most frequent value in an array? 

In [358]:
import numpy as np
array30 = np.random.randint(0,10,50)
print(np.bincount(array30).argmax())

3


### Quiz 84: Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [363]:
import numpy as np

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 2 4]
   [3 3 3]
   [2 0 1]]

  [[2 4 1]
   [3 3 3]
   [0 1 4]]

  [[4 1 3]
   [3 3 1]
   [1 4 3]]

  [[1 3 1]
   [3 1 3]
   [4 3 4]]

  [[3 1 3]
   [1 3 4]
   [3 4 2]]

  [[1 3 3]
   [3 4 1]
   [4 2 3]]

  [[3 3 2]
   [4 1 0]
   [2 3 4]]

  [[3 2 4]
   [1 0 4]
   [3 4 1]]]


 [[[3 3 3]
   [2 0 1]
   [1 0 1]]

  [[3 3 3]
   [0 1 4]
   [0 1 1]]

  [[3 3 1]
   [1 4 3]
   [1 1 0]]

  [[3 1 3]
   [4 3 4]
   [1 0 0]]

  [[1 3 4]
   [3 4 2]
   [0 0 3]]

  [[3 4 1]
   [4 2 3]
   [0 3 1]]

  [[4 1 0]
   [2 3 4]
   [3 1 1]]

  [[1 0 4]
   [3 4 1]
   [1 1 4]]]


 [[[2 0 1]
   [1 0 1]
   [3 4 4]]

  [[0 1 4]
   [0 1 1]
   [4 4 0]]

  [[1 4 3]
   [1 1 0]
   [4 0 0]]

  [[4 3 4]
   [1 0 0]
   [0 0 1]]

  [[3 4 2]
   [0 0 3]
   [0 1 0]]

  [[4 2 3]
   [0 3 1]
   [1 0 2]]

  [[2 3 4]
   [3 1 1]
   [0 2 2]]

  [[3 4 1]
   [1 1 4]
   [2 2 3]]]


 [[[1 0 1]
   [3 4 4]
   [0 2 4]]

  [[0 1 1]
   [4 4 0]
   [2 4 1]]

  [[1 1 0]
   [4 0 0]
   [4 1 2]]

  [[1 0 0]
   [0 0 1]
   [1 2 2]]

  [[0 0 3]
   

### Quiz 85:Create a 2D array subclass such that Z[i,j] == Z[j,i] 

In [369]:
import numpy as np
    
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  1  8 13 14]
 [ 1  6 10 12  4]
 [ 8 10  9 42 14]
 [13 12 42  7 13]
 [14  4 14 13  7]]


### Quiz 86: Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [370]:
import numpy as np
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


### quiz 87: Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

In [373]:
import numpy as np

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)
Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### Quiz 88: How to implement the Game of Life using numpy arrays? 

In [374]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
import numpy as np
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Quiz 89: How to get the n largest values of an array 

In [377]:
import numpy as np
array31 = np.arange(10000)
np.random.shuffle(array31)
n = 5
print (array31[np.argsort(array31)[-n:]])

[9995 9996 9997 9998 9999]


### Quoz 90: Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

In [378]:
import numpy as np
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### Quiz 91: How to create a record array from a regular array?  

In [379]:
import numpy as np
array32 = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
Record = np.core.records.fromarrays(array32.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Record)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### Quiz 92: Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [381]:
import numpy as np
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.24 s ± 139 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
466 ms ± 65.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
266 ms ± 18.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Quiz 93: Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?  

In [382]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 6 7]


### Quiz 94: Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [383]:
import numpy as np
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 0 0]
 [3 4 2]
 [1 2 0]
 [2 2 3]
 [3 2 2]
 [1 3 2]
 [3 4 3]
 [4 1 4]
 [4 3 0]
 [0 3 2]]
[[4 0 0]
 [3 4 2]
 [1 2 0]
 [2 2 3]
 [3 2 2]
 [1 3 2]
 [3 4 3]
 [4 1 4]
 [4 3 0]
 [0 3 2]]
[[4 0 0]
 [3 4 2]
 [1 2 0]
 [2 2 3]
 [3 2 2]
 [1 3 2]
 [3 4 3]
 [4 1 4]
 [4 3 0]
 [0 3 2]]


### Quiz 95: Convert a vector of ints into a matrix binary representation 

In [384]:
import numpy as np
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### Quiz 96: Given a two dimensional array, how to extract unique rows? 

In [385]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


### Quiz 97: Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 

In [387]:
import numpy as np
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)   


array([[0.42613617, 0.21944824, 0.45996961, 0.34637208, 0.37346658,
        0.07166681, 0.32119539, 0.28672516, 0.0913998 , 0.25902181],
       [0.39478591, 0.20330373, 0.42613027, 0.32088996, 0.34599115,
        0.06639438, 0.29756548, 0.26563118, 0.08467564, 0.23996593],
       [0.59027346, 0.30397437, 0.63713871, 0.47978619, 0.51731682,
        0.09927113, 0.44491205, 0.39716472, 0.12660478, 0.35879071],
       [0.61125947, 0.31478158, 0.65979093, 0.49684404, 0.53570901,
        0.10280052, 0.46073002, 0.41128513, 0.13110596, 0.37154681],
       [0.18717872, 0.09639182, 0.20203993, 0.15214264, 0.1640438 ,
        0.03147938, 0.14108387, 0.12594295, 0.04014702, 0.11377436],
       [0.6530858 , 0.33632097, 0.70493809, 0.53084133, 0.57236568,
        0.10983479, 0.49225615, 0.43942792, 0.14007708, 0.39697045],
       [0.59657737, 0.30722071, 0.64394313, 0.48491014, 0.52284158,
        0.10033131, 0.44966355, 0.4014063 , 0.12795687, 0.36262247],
       [0.28014633, 0.14426755, 0.3023887

### Quiz 98: Considering a path described by two vectors (X,Y), how to sample it using equidistant samples  

In [393]:
import numpy as np

# Example vectors describing the path
X = np.array([1, 2, 3, 4, 5])
Y = np.array([6, 7, 8, 9, 10])

# Number of equidistant samples
num_samples = 10

# Calculate the step size between samples
step_size = len(X) / (num_samples - 1)

# Generate the indices for sampling
indices = np.linspace(0, len(X)-1, num_samples, dtype=int)

# Sample the path using the indices
sampled_X = X[indices]
sampled_Y = Y[indices]

# Print the sampled coordinates
print(sampled_X)
print(sampled_Y)

[1 1 1 2 2 3 3 4 4 5]
[ 6  6  6  7  7  8  8  9  9 10]


### Quiz 99: Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 

In [394]:
import numpy as np
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


### Quiz 100: Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 

In [395]:
import numpy as np
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21314711  0.17921626]
